# Default initial positions for rm75_gripper_cameras's ros2_control fake system

initial_positions:
  gripper_finger1_joint: 0
  gripper_finger2_joint: 0
  gripper_finger1_link2_joint: 0
  gripper_finger2_link3_joint: 0
  gripper_finger1_tip_joint: 0
  gripper_finger2_tip_joint: 0
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0
  joint7: 0
