# Default initial positions for rm75_gripper_cameras's ros2_control fake system

initial_positions:
  gripper_finger1_joint: 0
  joint1: 0
  joint2: -0.8
  joint3: 0
  joint4: -0.8
  joint5: 0
  joint6: -1.57
  joint7: 0